repos:
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          args: [mixemup.py, test_mixemup.py]
          language_version: python3.7
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.1
      hooks:
        - id: flake8
          args: [mixemup.py, test_mixemup.py]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.701'
      hooks:
        - id: mypy