language: python

dist: xenial

python:
  - "3.7"

install:
  - scripts/travis_docker_build.sh
  - pip install twine

script:
  - docker create --name mixemup tonikarppi/mixemup:latest
  - docker cp mixemup:/app/dist dist

deploy:
  - provider: script
    skip_cleanup: true
    script: twine upload --skip-existing dist/*
    on:
      tags: true
      branch: master
  - provider: releases
    skip_cleanup: true
    draft: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
      tags: true
      branch: master
  - provider: script
    skip_cleanup: true
    script: scripts/travis_docker_deploy.sh
    on:
      branch: master

cache:
  pip: true

notifications:
  email: false