language: python

dist: xenial

python:
  - "3.7"

env:
  IMG=tonikarppi/mixemup

before_install:
  - docker pull $IMG:builder || true
  - docker pull $IMG:tester || true

install:
  - >
    docker build
    --target builder
    --cache-from $IMG:builder
    -t $IMG:builder .
  - >
    docker build
    --target tester
    --cache-from $IMG:tester
    -t $IMG:tester .
  - docker build -t $IMG:latest .
  - pip install twine

script:
  - docker create --name mixemup tonikarppi/mixemup:latest
  - docker cp mixemup:/app/dist dist

deploy:
  - provider: script
    skip_cleanup: true
    script: twine upload --skip-existing dist/*
    on:
      tags: true
      branch: master
  - provider: releases
    skip_cleanup: true
    draft: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
      tags: true
      branch: master
  - provider: script
    skip_cleanup: true
    script: sh .scripts/travis_deploy_docker.sh
    on:
      branch: master

cache:
  pip: true

notifications:
  email: false